spring.main.resources= classpath:/lib/
logging.file.name=./logs/my-app.log
server.port=8086
com.wfa.crosstalk.pubsub.kafkaServer=192.168.56.3:9092
com.wfa.crosstalk.pubsub.ksqlServer=192.168.56.3:9095
com.wfa.crosstalk.pubsub.schemaRegistryUrl=http://192.168.56.3:9094